Repository aya-prover/aya-dev, pull requests merged in 2021-10, with the labels that each got.

#58 Improve level solver error message
  base/src/main/java/org/aya/tyck/error/LevelMismatchError.java
  base/src/test/resources/failure/levels/refparo5.aya.txt
Labels: error report, universe polymorphism

#62 Add contribution guideline and code of conduct
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  bors.toml
Labels: documentation

#65 Enhance readme
  .github/README.md
Labels: documentation

#66 Remove the OMEGA universe and infinity level
  base/src/main/java/org/aya/core/serde/SerLevel.java
  base/src/main/java/org/aya/core/sort/Sort.java
  base/src/main/java/org/aya/core/term/FormTerm.java
  base/src/main/java/org/aya/generic/Level.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
  base/src/main/java/org/aya/tyck/unify/level/LevelEqnSet.java
  base/src/main/java/org/aya/tyck/unify/level/LevelSolver.java
  base/src/test/java/org/aya/experiments/ZzsSolver.java
Labels: universe polymorphism

#68 Set vendor in build script
  build.gradle.kts
Labels: build

#70 Thin white duke?
  base/src/main/java/org/aya/core/Meta.java
  base/src/main/java/org/aya/core/term/CallTerm.java
  base/src/main/java/org/aya/core/term/Term.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/test/resources/success/issues2/issue69.aya
Labels: meta variables

#72 Fix relative links
  .github/README.md
Labels: documentation
