Repository aya-prover/aya-dev, pull requests merged in 2022-04, with the labels that each got.

#356 Lazy `Term` visitor
  base/src/main/java/org/aya/core/Meta.java
  base/src/main/java/org/aya/core/def/Def.java
  base/src/main/java/org/aya/core/pat/Pat.java
  base/src/main/java/org/aya/core/pat/PatMatcher.java
  base/src/main/java/org/aya/core/pat/PatUnify.java
  base/src/main/java/org/aya/core/term/ElimTerm.java
  base/src/main/java/org/aya/core/term/Term.java
  base/src/main/java/org/aya/core/visitor/Renamer.java
  base/src/main/java/org/aya/core/visitor/Subst.java
  base/src/main/java/org/aya/core/visitor/Substituter.java
  base/src/main/java/org/aya/core/visitor/TermLift.java
  base/src/main/java/org/aya/core/visitor/TermMap.java
  base/src/main/java/org/aya/core/visitor/TermSubst.java
  base/src/main/java/org/aya/core/visitor/TermView.java
  base/src/main/java/org/aya/core/visitor/Unfolder.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/LittleTyper.java
  base/src/main/java/org/aya/tyck/pat/Conquer.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
  base/src/test/java/org/aya/core/SanityCheckTest.java
  buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
  note/unfiled.md
Labels: refactoring

#364 Less visitors
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/core/pat/Pat.java
  base/src/main/java/org/aya/core/term/Term.java
  base/src/main/java/org/aya/core/visitor/Renamer.java
  base/src/main/java/org/aya/core/visitor/TermLift.java
  base/src/main/java/org/aya/core/visitor/TermMap.java
  base/src/main/java/org/aya/core/visitor/TermOps.java
  base/src/main/java/org/aya/core/visitor/TermSubst.java
  base/src/main/java/org/aya/core/visitor/TermView.java
  base/src/main/java/org/aya/core/visitor/Unfolder.java
  base/src/main/java/org/aya/core/visitor/Zonker.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/Tycker.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
Labels: refactoring

#367 KALA: upgrade to 0.36.0
  base/src/main/java/org/aya/core/visitor/VarConsumer.java
  gradle/deps.properties
Labels: deps: kala

#368 REFACTOR: Migrate term lifting to the new API.
  base/src/main/java/org/aya/core/def/PrimDef.java
  base/src/main/java/org/aya/core/ops/Eta.java
  base/src/main/java/org/aya/core/serde/SerTerm.java
  base/src/main/java/org/aya/core/serde/Serializer.java
  base/src/main/java/org/aya/core/term/CallTerm.java
  base/src/main/java/org/aya/core/term/ElimTerm.java
  base/src/main/java/org/aya/core/visitor/Normalizer.java
  base/src/main/java/org/aya/core/visitor/TermFixpoint.java
  base/src/main/java/org/aya/core/visitor/TermOps.java
  base/src/main/java/org/aya/core/visitor/TermView.java
  base/src/main/java/org/aya/core/visitor/Unfolder.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
  base/src/test/java/org/aya/core/EtaTest.java
Labels: mcbride universe

#372 Cherry pick from Luna's tactic branch
  .github/workflows/commit-check.sh
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/TacNode.java
  base/src/main/java/org/aya/concrete/desugar/Desugarer.java
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
  base/src/main/java/org/aya/concrete/visitor/ExprOps.java
  base/src/main/java/org/aya/concrete/visitor/ExprView.java
  base/src/main/java/org/aya/concrete/visitor/StmtOps.java
  base/src/main/java/org/aya/core/visitor/TermOps.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
  pretty/src/main/java/org/aya/pretty/doc/Doc.java
Labels: concrete

#373 Tools
  base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
  base/src/main/java/org/aya/tyck/pat/MCT.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/test/java/org/aya/tyck/PatCCTest.java
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
  gradle/deps.properties
  note/early-changelog.md
  tools-repl/build.gradle.kts
  tools-repl/src/main/java/module-info.java
  tools-repl/src/main/java/org/aya/repl/antlr/AntlrUtil.java
  tools/src/main/java/org/aya/util/tyck/MCT.java
Labels: release

#379 Fix "no rule" reporting and ErrorExpr inference
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/error/NoRuleError.java
  base/src/test/resources/failure/operator/ambiguous.aya
  base/src/test/resources/failure/operator/ambiguous.aya.txt
  base/src/test/resources/failure/operator/no-assoc.aya
  base/src/test/resources/failure/operator/no-assoc.aya.txt
Labels: bug, error report

#380 Throws `InternalException` instead of `IllegalxxxException`
  base/src/main/java/org/aya/core/pat/Pat.java
  base/src/main/java/org/aya/core/pat/PatMatcher.java
  base/src/main/java/org/aya/core/pat/PatUnify.java
  base/src/main/java/org/aya/core/serde/Serializer.java
  base/src/main/java/org/aya/generic/util/InternalException.java
  base/src/main/java/org/aya/resolve/module/EmptyModuleLoader.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
  base/src/main/java/org/aya/terck/CallMatrix.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/env/LocalCtx.java
  base/src/main/java/org/aya/tyck/error/CircularSignatureError.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
  cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
  cli/src/main/java/org/aya/cli/library/json/LibraryDependencyData.java
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
  lsp/src/main/java/org/aya/lsp/utils/Log.java
Labels: error report

#371 Move primitive related states to `TyckState`
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/core/def/PrimDef.java
  base/src/main/java/org/aya/core/pat/PatMatcher.java
  base/src/main/java/org/aya/core/serde/CompiledAya.java
  base/src/main/java/org/aya/core/serde/SerDef.java
  base/src/main/java/org/aya/core/serde/SerTerm.java
  base/src/main/java/org/aya/core/term/Term.java
  base/src/main/java/org/aya/core/visitor/TermOps.java
  base/src/main/java/org/aya/core/visitor/TermView.java
  base/src/main/java/org/aya/core/visitor/Unfolder.java
  base/src/main/java/org/aya/core/visitor/Zonker.java
  base/src/main/java/org/aya/resolve/ResolveInfo.java
  base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
  base/src/main/java/org/aya/resolve/module/ModuleLoader.java
  base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/error/BadTypeError.java
  base/src/main/java/org/aya/tyck/error/UnifyError.java
  base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
  base/src/main/java/org/aya/tyck/pat/Conquer.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/test/java/org/aya/concrete/DesugarTest.java
  base/src/test/java/org/aya/concrete/VisitorTest.java
  base/src/test/java/org/aya/core/DistillerTest.java
  base/src/test/java/org/aya/core/NormalizeTest.java
  base/src/test/java/org/aya/core/SuedeTest.java
  base/src/test/java/org/aya/core/UsagesTest.java
  base/src/test/java/org/aya/experiments/NormalizeHugeChurch.java
  base/src/test/java/org/aya/test/LibraryTest.java
  base/src/test/java/org/aya/test/TestRunner.java
  base/src/test/java/org/aya/tyck/PatCCTest.java
  base/src/test/java/org/aya/tyck/TracingTest.java
  base/src/test/java/org/aya/tyck/TyckDeclTest.java
  cli/src/main/java/org/aya/cli/Main.java
  cli/src/main/java/org/aya/cli/library/LibraryCompiler.java
  cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
  cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
  cli/src/main/java/org/aya/cli/single/SingleFileCompiler.java
  cli/src/main/java/org/aya/cli/utils/AyaCompiler.java
  lsp/src/main/java/org/aya/lsp/actions/ComputeTerm.java
  lsp/src/main/java/org/aya/lsp/server/AyaServer.java
  lsp/src/main/java/org/aya/lsp/server/AyaService.java
Labels: primitives

#385 Cherry pick
  base/src/main/java/org/aya/core/term/Term.java
  base/src/main/java/org/aya/tyck/LittleTyper.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/error/NobodyError.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
  base/src/test/resources/failure/patterns/issues2/issue384.aya
  base/src/test/resources/failure/patterns/issues2/issue384.aya.txt
  cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
Labels: bug, refactoring, repl

#374 Rewrite ExprResolver with pattern matching
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/desugar/Desugarer.java
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
Labels: resolving

#389 Fix nightly build
  .github/workflows/nightly-build.yml
Labels: build

#392 Cherry pick
  .editorconfig
  .github/workflows/commit-check.yml
  .github/workflows/gradle-check.yml
  .github/workflows/nightly-build.yml
  base/src/main/java/org/aya/generic/util/InternalException.java
  cli/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
Labels: cherry-pick

#399 REPL enhancement
  cli/src/main/java/org/aya/cli/repl/ReplCompiler.java
  cli/src/main/java/org/aya/cli/repl/ReplContext.java
  cli/src/main/java/org/aya/cli/utils/RepoLike.java
  cli/src/test/java/org/aya/cli/ReplCompilerTest.java
Labels: repl

#401 Code Shape Matcher
  base/src/main/java/module-info.java
  base/src/main/java/org/aya/core/repr/AyaShape.java
  base/src/main/java/org/aya/core/repr/CodeShape.java
  base/src/main/java/org/aya/core/repr/ShapeMatcher.java
  base/src/test/java/org/aya/repr/ShapeMatcherTest.java
Labels: cherry-pick

#402 Add `NotAnIntervalError`
  base/src/main/java/org/aya/tyck/error/NotAnIntervalError.java
Labels: cherry-pick
