Repository aya-prover/aya-dev, pull requests merged in 2022-03, with the labels that each got.

#326 Mutual recursion on constructors and fields
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/concrete/remark/Remark.java
  base/src/main/java/org/aya/concrete/stmt/Decl.java
  base/src/main/java/org/aya/concrete/stmt/Sample.java
  base/src/main/java/org/aya/resolve/ResolveInfo.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/order/AyaOrgaTycker.java
  base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
  base/src/main/java/org/aya/tyck/order/SigRefFinder.java
  base/src/main/java/org/aya/tyck/order/TyckOrder.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/test/resources/failure/holes/ulf-hole-illtype.aya.txt
  base/src/test/resources/failure/implicit/implicit2.aya.txt
  base/src/test/resources/failure/patterns/issues2/issue250.aya
  base/src/test/resources/failure/patterns/issues2/issue250.aya.txt
  base/src/test/resources/success/src/Refparo/19.aya
  base/src/test/resources/success/src/Refparo/7.aya
  base/src/test/resources/success/src/Refparo/Demo.aya
  base/src/test/resources/success/src/Refparo/Model.aya
  tools/src/main/java/org/aya/util/MutableGraph.java
Labels: tyck order

#330 Misc
  base/src/main/java/org/aya/core/ops/Eta.java
  base/src/main/java/org/aya/distill/ConcreteDistiller.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
Labels: refactoring

#331 Constructors and fields should explicitly depend on their top-level decls.
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
Labels: test fixtures, tyck order

#333 Blah blah blah
  .github/README.md
  .github/workflows/gradle-check.yml
  base/src/main/java/org/aya/concrete/desugar/Desugarer.java
  build.gradle.kts
  gradle/deps.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: build

#340 RefTerms in the header should depend on the whole referred body (#337)
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/test/resources/success/src/Issues/337.aya
Labels: test fixtures, tyck order

#342 Make LSP work again!
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
  base/src/main/java/org/aya/distill/ConcreteDistiller.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
  lsp/build.gradle.kts
  lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
  lsp/src/main/java/org/aya/lsp/utils/Resolver.java
Labels: lsp

#344 Substitute patterns for variables in telescope
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/visitor/ExprConsumer.java
  base/src/main/java/org/aya/concrete/visitor/ExprFixpoint.java
  base/src/main/java/org/aya/core/pat/Pat.java
  base/src/main/java/org/aya/core/pat/PatToTerm.java
  base/src/main/java/org/aya/distill/ConcreteDistiller.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/test/resources/success/src/Issues/339.aya
  base/src/test/resources/success/src/Refparo/Model.aya
Labels: tyck: pattern

#347 Use better source pos
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/test/resources/success/common/src/Data/Unit.aya
  base/src/test/resources/success/src/Issues/339.aya
  base/src/test/resources/success/src/Issues/346.aya
  tools/src/main/java/org/aya/util/error/SourcePos.java
Labels: bug

#348 Also lift struct fields
  base/src/main/java/org/aya/core/visitor/Substituter.java
  base/src/main/java/org/aya/core/visitor/Unfolder.java
  base/src/main/java/org/aya/distill/ConcreteDistiller.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/test/resources/success/src/Issues/336.aya
Labels: bug, mcbride universe

#350 Ensure pi body normalized
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/error/LevelError.java
  base/src/test/resources/failure/levels/refparo5.aya.txt
  base/src/test/resources/failure/levels/too-high.aya.txt
  base/src/test/resources/failure/tyck/issues/issue697.aya.txt
Labels: bug

#351 Replace sample declarations with modifiers
  base/src/main/java/org/aya/concrete/stmt/Command.java
  base/src/main/java/org/aya/concrete/stmt/Decl.java
  base/src/main/java/org/aya/concrete/stmt/Generalize.java
  base/src/main/java/org/aya/concrete/stmt/Sample.java
  base/src/main/java/org/aya/concrete/stmt/Stmt.java
  base/src/main/java/org/aya/concrete/visitor/StmtConsumer.java
  base/src/main/java/org/aya/concrete/visitor/StmtFixpoint.java
  base/src/main/java/org/aya/distill/BaseDistiller.java
  base/src/main/java/org/aya/distill/ConcreteDistiller.java
  base/src/main/java/org/aya/generic/ref/GeneralizedVar.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
  base/src/main/java/org/aya/tyck/error/CircularSignatureError.java
  base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
  base/src/test/java/org/aya/tyck/TracingTest.java
  buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
  lsp/src/main/java/org/aya/lsp/actions/SyntaxHighlight.java
Labels: developer experience

#353 Fix crash on no patterns
  base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/main/java/org/aya/tyck/pat/PatTycker.java
  base/src/test/resources/failure/patterns/issues2/issue352.aya
  base/src/test/resources/failure/patterns/issues2/issue352.aya.txt
  note/early-changelog.md
Labels: coverage

#354 Lift a meta and unlift the solution
  base/src/main/java/org/aya/core/Meta.java
  base/src/main/java/org/aya/core/term/CallTerm.java
  base/src/main/java/org/aya/core/visitor/TermConsumer.java
  base/src/main/java/org/aya/core/visitor/TermFixpoint.java
  base/src/main/java/org/aya/tyck/env/LocalCtx.java
  base/src/main/java/org/aya/tyck/unify/DefEq.java
Labels: meta variables

#355 Bump version to 0.16, update javadoc
  base/src/main/java/org/aya/core/pat/PatUnify.java
  base/src/main/java/org/aya/core/term/ErrorTerm.java
  gradle/deps.properties
  note/early-changelog.md
Labels: release

#359 Fix grammar
  base/src/test/resources/failure/syntax/issue164.aya.txt
  base/src/test/resources/failure/syntax/issue165.aya.txt
  buildSrc/src/main/antlr/org/aya/parser/AyaLexer.g4
  buildSrc/src/main/antlr/org/aya/parser/AyaParser.g4
  cli/src/main/java/org/aya/cli/parse/AyaProducer.java
Labels: bug

#360 Use adaptive-cli style whenever outputting to a terminal
  base/src/test/java/org/aya/concrete/DesugarTest.java
  base/src/test/java/org/aya/concrete/ParseTest.java
  base/src/test/java/org/aya/literate/LiterateTest.java
  base/src/test/java/org/aya/test/LibraryTest.java
  base/src/test/java/org/aya/test/StreamReporter.java
  base/src/test/java/org/aya/test/ThrowingReporter.java
  base/src/test/java/org/aya/tyck/PatCCTest.java
  base/src/test/java/org/aya/tyck/TyckDeclTest.java
  cli/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
  cli/src/main/java/org/aya/cli/single/CliReporter.java
  cli/src/test/java/org/aya/cli/ReplParserTest.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinterConfig.java
  pretty/src/main/java/org/aya/pretty/backend/string/style/UnixTermStylist.java
  pretty/src/main/java/org/aya/pretty/printer/Stylist.java
  pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java
  tools/src/main/java/org/aya/util/reporter/ThrowingReporter.java
Labels: bug
