Repository aya-prover/aya-dev, pull requests merged in 2023-04, with the labels that each got.

#948 Show compiler diagnostics in literate output
  base/src/main/java/org/aya/prettier/BasePrettier.java
  base/src/main/java/org/aya/tyck/pat/ClausesProblem.java
  base/src/test/java/org/aya/literate/AyaMdParserTest.java
  base/src/test/java/org/aya/literate/FaithfulPrettierTest.java
  base/src/test/java/org/aya/literate/HighlighterTester.java
  base/src/test/java/org/aya/test/EmptyModuleLoader.java
  base/src/test/resources/failure/patterns/confl-literal.aya.txt
  base/src/test/resources/failure/patterns/confl-literal2.aya.txt
  base/src/test/resources/failure/patterns/confl.aya.txt
  base/src/test/resources/failure/patterns/issues/issue302.aya.txt
  base/src/test/resources/failure/patterns/issues/issue354-confl.aya.txt
  base/src/test/resources/failure/patterns/issues/issue354-reduce.aya.txt
  base/src/test/resources/failure/patterns/issues/issue366.aya.txt
  base/src/test/resources/failure/patterns/literal-conf.aya.txt
  base/src/test/resources/literate/compiler-output.aya.md
  cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
  cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
  cli-impl/src/main/java/org/aya/cli/literate/HighlightsCollector.java
  cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
  cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
  cli-impl/src/main/java/org/aya/cli/single/SingleFileCompiler.java
  cli-impl/src/main/java/org/aya/cli/utils/InlineHintProblem.java
  ide-lsp/src/main/java/org/aya/lsp/models/HighlightResult.java
  ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
  pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
  pretty/src/main/java/org/aya/pretty/backend/html/HtmlConstants.java
  pretty/src/main/java/org/aya/pretty/backend/latex/TeXStylist.java
  pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/md/MdStylist.java
  pretty/src/main/java/org/aya/pretty/backend/string/ClosingStylist.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/terminal/DocTermPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/terminal/UnixTermStylist.java
  pretty/src/main/java/org/aya/pretty/doc/Doc.java
  pretty/src/main/java/org/aya/pretty/doc/Style.java
  pretty/src/main/java/org/aya/pretty/style/AyaColorScheme.java
  pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java
  pretty/src/main/java/org/aya/pretty/style/AyaStyleKey.java
  pretty/src/main/resources/aya-html/highlight-fn.js
  pretty/src/main/resources/aya-html/highlight-occurrences.js
  pretty/src/main/resources/aya-html/hover-tooltip.css
  pretty/src/main/resources/aya-html/hover.css
  pretty/src/main/resources/aya-html/katex-auto-render.js
  pretty/src/main/resources/aya-html/katex.html
  pretty/src/main/resources/aya-html/show-tooltip-fn.js
  pretty/src/main/resources/aya-html/show-tooltip.js
  tools/src/main/java/org/aya/util/reporter/CollectingReporter.java
  tools/src/main/java/org/aya/util/reporter/Problem.java
Labels: feature, literate

#954 Merge Carefully
  cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
Labels: bug

#956 Upgrade deps, update readme
  .github/README.md
  gradle/deps.properties
Labels: build

#960 Simplify `Context::bind`
  base/src/main/java/org/aya/resolve/context/Context.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
Labels: refactoring

#961 Cherry-pick from cartesian-kan-ops development
  base/src/main/java/org/aya/core/def/PrimDef.java
  base/src/main/java/org/aya/core/meta/Meta.java
  base/src/main/java/org/aya/core/meta/MetaInfo.java
  base/src/main/java/org/aya/core/pat/Pat.java
  base/src/main/java/org/aya/core/repr/AyaShape.java
  base/src/main/java/org/aya/core/repr/CodeShape.java
  base/src/main/java/org/aya/core/serde/SerPat.java
  base/src/main/java/org/aya/core/serde/SerTerm.java
  base/src/main/java/org/aya/core/serde/Serializer.java
  base/src/main/java/org/aya/core/term/IntervalTerm.java
  base/src/main/java/org/aya/core/term/PathTerm.java
  base/src/main/java/org/aya/core/term/PiTerm.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/unify/Unifier.java
Labels: refactoring

#964 KALA: upgrade to 0.65.0
  gradle/deps.properties
Labels: deps: kala

#963 Checked Let
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/test/resources/failure/syntax/let-expr2.aya.txt
  base/src/test/resources/success/src/Issues/CheckedLet.aya
Labels: bug, tyck

#959 Literate library
  base/src/main/java/org/aya/concrete/Expr.java
  base/src/main/java/org/aya/concrete/desugar/Desugarer.java
  base/src/main/java/org/aya/concrete/visitor/StmtFolder.java
  base/src/main/java/org/aya/core/serde/CompiledAya.java
  base/src/main/java/org/aya/core/serde/SerDef.java
  base/src/main/java/org/aya/core/serde/SerTerm.java
  base/src/main/java/org/aya/core/serde/Serializer.java
  base/src/main/java/org/aya/generic/util/AyaFiles.java
  base/src/main/java/org/aya/prettier/BasePrettier.java
  base/src/main/java/org/aya/ref/DefVar.java
  base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtShallowResolver.java
  base/src/test/java/org/aya/literate/AyaMdParserTest.java
  base/src/test/java/org/aya/literate/FaithfulPrettierTest.java
  base/src/test/java/org/aya/literate/HighlighterTest.java
  base/src/test/java/org/aya/literate/HighlighterTester.java
  base/src/test/java/org/aya/test/LibraryTest.java
  base/src/test/resources/success/aya.json
  base/src/test/resources/success/src/Literate/Syntax.aya.md
  build.gradle.kts
  buildSrc/src/main/groovy/org/aya/gradle/CommonTasks.groovy
  cli-console/src/main/java/org/aya/cli/console/Main.java
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-console/src/main/java/org/aya/cli/repl/jline/JlineRepl.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplConfig.java
  cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
  cli-impl/src/main/java/org/aya/cli/library/LibraryModuleLoader.java
  cli-impl/src/main/java/org/aya/cli/library/json/LibraryConfig.java
  cli-impl/src/main/java/org/aya/cli/library/json/LibraryConfigData.java
  cli-impl/src/main/java/org/aya/cli/library/source/DiskLibraryOwner.java
  cli-impl/src/main/java/org/aya/cli/library/source/LibrarySource.java
  cli-impl/src/main/java/org/aya/cli/library/source/MutableLibraryOwner.java
  cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
  cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
  cli-impl/src/main/java/org/aya/cli/parse/AyaParserImpl.java
  cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
  cli-impl/src/main/java/org/aya/cli/render/RenderOptions.java
  cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
  cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  cli-impl/src/main/java/org/aya/cli/utils/LiteratePrettierOptions.java
  cli-impl/src/test/java/org/aya/cli/RenderOptionsTest.java
  cli-impl/src/test/java/org/aya/cli/ReplConfigTest.java
  ide-lsp/build.gradle.kts
  ide-lsp/src/main/java/org/aya/lsp/actions/SemanticHighlight.java
  ide-lsp/src/main/java/org/aya/lsp/library/WsLibrary.java
  ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
  ide/src/main/java/org/aya/ide/action/GotoDefinition.java
  pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinterConfig.java
  pretty/src/main/java/org/aya/pretty/doc/Link.java
  tools/src/main/java/org/aya/util/FileUtil.java
Labels: literate, library

#965 Follow up fixes
  base/src/main/java/org/aya/core/visitor/BetaExpander.java
Labels: cartesian cubical

#966 Lazily compute types on demand
  .github/README.md
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/Result.java
Labels: performance

#968 Upgrade dependency, supersede a util method
  .github/workflows/nightly-build.yml
  base/src/main/java/module-info.java
  base/src/main/java/org/aya/concrete/remark/AyaLiterate.java
  base/src/main/java/org/aya/concrete/remark/CodeAttrProcessor.java
  base/src/main/java/org/aya/concrete/remark/CodeOptions.java
  base/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
  gradle/deps.properties
  gradle/wrapper/gradle-wrapper.properties
  parser/src/main/java/org/aya/parser/GenericNode.java
  pretty/src/main/java/module-info.java
  tools-md/src/main/java/module-info.java
  tools-repl/src/main/java/module-info.java
  tools/build.gradle.kts
  tools/src/main/java/module-info.java
  tools/src/main/java/org/aya/util/StringUtil.java
  tools/src/main/java/org/aya/util/error/SourceFile.java
Labels: refactoring

#970 fix: do not print `aya-hidden` (#969)
  base/src/main/java/org/aya/concrete/GenericAyaFile.java
  base/src/main/java/org/aya/concrete/remark/AyaLiterate.java
  base/src/main/java/org/aya/concrete/remark/CodeOptions.java
  cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
  cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  tools-md/src/main/java/org/aya/literate/Literate.java
  tools-md/src/main/java/org/aya/literate/parser/BaseMdParser.java
Labels: literate
