Repository aya-prover/aya-dev, pull requests merged in 2023-03, with the labels that each got.

#938 Fix: graal build
  base/reflect-config.txt
  base/src/main/java/org/aya/resolve/context/ModuleName.java
  cli-impl/src/main/java/org/aya/cli/single/SingleAyaFile.java
  cli-impl/src/main/java/org/aya/cli/single/SingleFileCompiler.java
Labels: build

#939 Rewrite some garbages and fix some problems
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/test/java/org/aya/literate/AyaMdParserTest.java
  base/src/test/resources/literate/.gitignore
  base/src/test/resources/literate/expected-test.aya
  base/src/test/resources/literate/expected-wow.aya
  cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
  cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
Labels: highlighter

#941 Release 0.28
  buildSrc/src/main/groovy/org/aya/gradle/JFlexTask.groovy
  gradle/deps.properties
  note/early-changelog.md
  parser/src/main/grammar/AyaPsiLexer.flex
  pretty/src/main/java/org/aya/pretty/doc/Docile.java
  pretty/src/main/java/org/aya/pretty/error/LineColSpan.java
  tools/src/main/java/org/aya/util/error/WithPos.java
Labels: release

#943 More Stdlib + Misc
  base/src/test/resources/failure/syntax/overlap-def.aya
  base/src/test/resources/failure/syntax/overlap-def.aya.txt
  base/src/test/resources/success/common/src/Arith/Bool.aya
  base/src/test/resources/success/common/src/Arith/Bool/Core.aya
  base/src/test/resources/success/common/src/Arith/Bool/Properties.aya
  base/src/test/resources/success/common/src/Arith/Fin/Core.aya
  base/src/test/resources/success/common/src/Arith/Fin/Properties.aya
  base/src/test/resources/success/common/src/Arith/Nat/Equality.aya
  base/src/test/resources/success/common/src/Arith/Nat/Order.aya
  base/src/test/resources/success/common/src/Arith/Nat/Properties.aya
  base/src/test/resources/success/common/src/Logic/Dec.aya
  base/src/test/resources/success/common/src/Logic/False.aya
  base/src/test/resources/success/common/src/Logic/Reflect.aya
  cli-impl/src/main/java/org/aya/cli/parse/AyaProducer.java
Labels: error report, parser

#945 Java's Override doesn't work!!
  base/src/main/java/org/aya/resolve/context/NoExportContext.java
  base/src/main/java/org/aya/resolve/context/PhysicalModuleContext.java
Labels: bug

#946 Make LSP Colorful Again
  cli-impl/src/main/java/org/aya/cli/render/RenderOptions.java
  ide-lsp/src/main/java/org/aya/lsp/models/ServerOptions.java
  ide-lsp/src/main/java/org/aya/lsp/models/ServerRenderOptions.java
  ide-lsp/src/main/java/org/aya/lsp/server/AyaLanguageServer.java
  ide-lsp/src/test/java/org/aya/lsp/LspTest.java
  ide-lsp/src/test/java/org/aya/lsp/tester/LspTestClient.java
Labels: feature, lsp

#947 Support LaTeX math formula in literate mode
  base/src/main/java/module-info.java
  base/src/main/java/org/aya/concrete/error/OperatorError.java
  base/src/main/java/org/aya/concrete/remark/Literate.java
  base/src/main/java/org/aya/concrete/remark/code/CodeAttrProcessor.java
  base/src/main/java/org/aya/concrete/remark/code/CodeOptions.java
  base/src/main/java/org/aya/concrete/remark/math/InlineMath.java
  base/src/main/java/org/aya/concrete/remark/math/MathBlock.java
  base/src/main/java/org/aya/resolve/error/NameProblem.java
  base/src/main/java/org/aya/resolve/error/PrimResolveError.java
  base/src/main/java/org/aya/tyck/error/BadTypeError.java
  base/src/main/java/org/aya/tyck/error/FieldError.java
  base/src/test/java/org/aya/literate/AyaMdParserTest.java
  base/src/test/resources/literate/.gitignore
  base/src/test/resources/literate/syntax.aya.md
  cli-impl/src/main/java/org/aya/cli/literate/AyaMdParser.java
  pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/html/HtmlConstants.java
  pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/terminal/DocTermPrinter.java
  pretty/src/main/java/org/aya/pretty/doc/Doc.java
  pretty/src/main/java/org/aya/pretty/doc/Language.java
  pretty/src/test/java/org/aya/pretty/MdStyleTest.java
  pretty/src/test/java/org/aya/pretty/Reproduction.java
Labels: literate
