Repository aya-prover/aya-dev, pull requests merged in 2024-11, with the labels that each got.

#1135 Refactor Module
  base/src/main/java/org/aya/resolve/ResolveInfo.java
  base/src/main/java/org/aya/resolve/context/Candidate.java
  base/src/main/java/org/aya/resolve/context/ModuleContext.java
  base/src/main/java/org/aya/resolve/context/ModuleExport.java
  base/src/main/java/org/aya/resolve/context/ModuleSymbol.java
  base/src/main/java/org/aya/resolve/context/PhysicalModuleContext.java
  base/src/main/java/org/aya/resolve/error/NameProblem.java
  base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
  build.gradle.kts
  cli-console/src/main/java/org/aya/cli/repl/jline/AyaCompleters.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java
  cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/resources/negative/ScopeError.txt
  jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/ModuleName.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/UseHide.java
  tools-kala/src/main/java/org/aya/util/binop/Assoc.java
  tools-kala/src/main/java/org/aya/util/binop/BinOpSet.java
  tools-repl/src/main/java/org/aya/repl/ReplParser.java
Labels: refactoring

#1136 Dependency upgrades
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  tools-md/src/main/java/org/aya/literate/parser/FillCodeBlock.java
Labels: deps: jline, deps: upstream

#1138 Jit class cp
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/test/java/org/aya/tyck/TyckTest.java
  cli-impl/src/test/java/org/aya/test/LibraryTest.java
  cli-impl/src/test/resources/success/src/Classes.aya
  gradle/libs.versions.toml
  ide-lsp/build.gradle.kts
  jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ClassSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitDefSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/MemberSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PrimSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  syntax/src/main/java/org/aya/syntax/compile/JitClass.java
  syntax/src/main/java/org/aya/syntax/compile/JitDef.java
  syntax/src/main/java/org/aya/syntax/compile/JitMember.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDef.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDefLike.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
Labels: cherry-pick

#1139 Jit class cp 2
  base/src/test/java/org/aya/tyck/TyckTest.java
  syntax/src/main/java/org/aya/syntax/compile/JitClass.java
  syntax/src/main/java/org/aya/syntax/compile/JitMember.java
  syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDefLike.java
Labels: cherry-pick, classes

#1140 Prepare for Java 23, improve tests, fix some classes codegen errors
  base/src/main/java/org/aya/resolve/context/Candidate.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/error/TupleError.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  base/src/main/java/org/aya/unify/TermComparator.java
  base/src/test/java/org/aya/tyck/TyckTest.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
  cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
  cli-impl/src/test/java/org/aya/test/LibraryTest.java
  cli-impl/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/test/java/org/aya/test/cli/LibraryGraphTest.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/java/org/aya/test/literate/AyaMdParserTest.java
  cli-impl/src/test/java/org/aya/test/literate/HighlighterTester.java
  cli-impl/src/test/resources/negative/ScopeError.txt
  ide-lsp/src/test/java/org/aya/lsp/LspTest.java
  jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ClassSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
  jit-compiler/src/main/java/org/aya/compiler/FileSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitDefSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PrimSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/test/java/MiscTest.java
  jit-compiler/src/test/java/Profiler.java
  pretty/src/main/java/org/aya/pretty/backend/html/DocHtmlPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/html/Html5Stylist.java
  producer/src/main/java/org/aya/producer/AyaParserImpl.java
  syntax/src/main/java/org/aya/generic/Renamer.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/compile/JitClass.java
  syntax/src/main/java/org/aya/syntax/compile/JitDef.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/term/ClassCastTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/LamTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ClassCall.java
  tools-kala/src/main/java/org/aya/util/terck/Relation.java
  tools-repl/src/main/java/org/aya/repl/CommandManager.java
  tools-repl/src/main/java/org/aya/repl/ReplUtil.java
  tools/src/main/java/org/aya/util/Scoped.java
  tools/src/main/java/org/aya/util/Version.java
  tools/src/main/java/org/aya/util/error/SourcePos.java
  tools/src/main/java/org/aya/util/reporter/ThrowingReporter.java
Labels: cherry-pick, classes, java, jit

#1141 Generate dummy terms
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/term/ClassCastTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/call/MemberCall.java
Labels: classes

#1147 Fix two issues related to arrays and meta lit terms, implement `debug-show-shapes`
  base/src/main/java/org/aya/normalize/Normalizer.java
  base/src/main/java/org/aya/normalize/error/UnsolvedLit.java
  base/src/main/java/org/aya/resolve/module/ModuleLoader.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  cli-impl/src/test/resources/success/src/Test.aya
  cli-impl/src/test/resources/success/src/TestNoExtraLists.aya
  jit-compiler/src/test/resources/TreeSort.aya
  syntax/src/main/java/org/aya/syntax/core/term/repr/MetaLitTerm.java
Labels: bug, literal

#1148 Error handling, handle `RuleReducer.Con` in `visibleArgs` in `CorePrettier`
  base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
  cli-impl/src/main/java/org/aya/cli/utils/CompilerUtil.java
  cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
  gradle/libs.versions.toml
  note/early-changelog.md
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
Labels: bug

#1152 Option to disable prelude
  base/src/main/java/org/aya/primitive/PrimFactory.java
  base/src/main/java/org/aya/resolve/context/ModuleContext.java
  base/src/main/java/org/aya/resolve/salt/Desalt.java
  base/src/main/java/org/aya/resolve/salt/ExprBinParser.java
  base/src/main/java/org/aya/resolve/salt/PatternBinParser.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/PatternResolver.java
  base/src/main/java/org/aya/tyck/error/ClausesProblem.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/unify/Synthesizer.java
  base/src/main/java/org/aya/unify/TermComparator.java
  cli-console/src/main/java/module-info.java
  cli-console/src/main/java/org/aya/cli/console/Main.java
  cli-console/src/main/java/org/aya/cli/console/MainArgs.java
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplConfig.java
  cli-impl/src/main/java/org/aya/cli/render/vscode/ColorTheme.java
  ide-lsp/src/main/java/org/aya/lsp/models/HighlightResult.java
  jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  note/old/glossary.md
  parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
  parser/src/main/gen/org/aya/parser/AyaPsiParser.java
  parser/src/main/grammar/AyaPsiParser.bnf
  pretty/src/main/java/org/aya/pretty/backend/string/ClosingStylist.java
  pretty/src/main/java/org/aya/pretty/error/PrettyError.java
  syntax/src/main/java/org/aya/generic/stmt/Shaped.java
  syntax/src/main/java/org/aya/generic/stmt/TyckOrder.java
  syntax/src/main/java/org/aya/syntax/compile/JitPrim.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/FnBody.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDef.java
  syntax/src/main/java/org/aya/syntax/core/pat/PatMatcher.java
  syntax/src/main/java/org/aya/syntax/ref/QPath.java
  tools-kala/src/main/java/org/aya/util/terck/Relation.java
  tools-repl/build.gradle.kts
  tools-repl/src/main/java/module-info.java
Labels: repl, cli

#1153 Add something without thinking
  base/src/main/java/org/aya/tyck/ExprTycker.java
  gradle/libs.versions.toml
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  syntax/src/main/java/org/aya/syntax/core/term/ClassCastTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/call/MemberCall.java
Labels: classes

#1156 Binary tuple & combine pi and sigma into depType
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/error/PatternProblem.java
  base/src/main/java/org/aya/tyck/error/TupleError.java
  base/src/main/java/org/aya/tyck/pat/PatClassifier.java
  base/src/main/java/org/aya/tyck/pat/PatUnify.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  base/src/main/java/org/aya/unify/DoubleChecker.java
  base/src/main/java/org/aya/unify/Synthesizer.java
  base/src/main/java/org/aya/unify/TermComparator.java
  cli-console/src/main/java/org/aya/cli/console/Main.java
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
  cli-impl/src/test/resources/success/src/Test.aya
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ClassSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
  jit-compiler/src/main/java/org/aya/compiler/JitDefSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/MemberSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/test/java/CompileTester.java
  jit-compiler/src/test/java/MiscTest.java
  pretty/src/main/java/org/aya/pretty/doc/Doc.java
  pretty/src/test/java/org/aya/pretty/DocStringPrinterTest.java
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/generic/Renamer.java
  syntax/src/main/java/org/aya/generic/term/DTKind.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/concrete/Expr.java
  syntax/src/main/java/org/aya/syntax/concrete/Pattern.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/def/PrimDef.java
  syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
  syntax/src/main/java/org/aya/syntax/core/pat/PatMatcher.java
  syntax/src/main/java/org/aya/syntax/core/pat/PatToTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/DepTypeTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/ProjTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/SigmaTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/TupTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/call/MetaCall.java
  syntax/src/main/java/org/aya/syntax/core/term/marker/Formation.java
  syntax/src/main/java/org/aya/syntax/core/term/marker/StableWHNF.java
  syntax/src/main/java/org/aya/syntax/core/term/repr/IntegerOps.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
  syntax/src/main/java/org/aya/syntax/telescope/Signature.java
  tools-kala/src/main/java/org/aya/util/tyck/pat/ClassifierUtil.java
Labels: concrete, core: pattern, concrete: pattern

#1158 Simplify concrete
  base/src/main/java/org/aya/resolve/salt/Desalt.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  syntax/src/main/java/org/aya/syntax/concrete/Expr.java
Labels: concrete

#1159 Usage analy in jit compiler
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  syntax/src/main/java/org/aya/syntax/core/Closure.java
  tools/src/main/java/org/aya/util/error/Global.java
Labels: performance, jit

#1164 Use latest build-util
  build.gradle.kts
  gradle/libs.versions.toml
Labels: deps: upstream

#1163 dev: update flake.lock
  flake.lock
Labels: nix

#1165 Cherry pick from class resolver
  base/src/main/java/org/aya/tyck/ArgsComputer.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
Labels: cherry-pick

#1166 Fix #1155
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/test/java/org/aya/syntax/core/PrettierTest.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/core/RichParam.java
  syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
  syntax/src/main/java/org/aya/syntax/core/term/Param.java
  syntax/src/main/java/org/aya/syntax/core/term/Term.java
Labels: pretty print

#1167 Fix 1135
  base/src/main/java/org/aya/resolve/visitor/StmtBinder.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  cli-impl/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/test/java/org/aya/test/fixtures/OperatorError.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/java/org/aya/test/fixtures/TerckError.java
  cli-impl/src/test/resources/negative/OperatorError.txt
  cli-impl/src/test/resources/negative/ScopeError.txt
  cli-impl/src/test/resources/negative/TerckError.txt
  cli-impl/src/test/resources/shared/src/data/unit.aya
  cli-impl/src/test/resources/shared/src/data/unit/base.aya
Labels: bug, resolving
