Repository aya-prover/aya-dev, pull requests merged in 2024-06, with the labels that each got.

#1073 Increase test coverage
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/error/HoleProblem.java
  base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
  cli-impl/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/test/java/org/aya/test/fixtures/ParseError.java
  cli-impl/src/test/resources/negative/ParseError.txt
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/generic/Nested.java
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
Labels: parser, test fixtures

#1074 Refactor of jit-compiler
  base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
  base/src/test/java/org/aya/tyck/PatternTyckTest.java
  jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
  jit-compiler/src/main/java/org/aya/compiler/FileSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PrimSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/test/java/CompileTest.java
Labels: refactoring, jit

#1075 Make hoshino-said work
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
  base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  cli-impl/src/test/java/org/aya/test/literate/AyaMdParserTest.java
  cli-impl/src/test/resources/literate/hoshino-said.aya.md
  syntax/src/main/java/org/aya/syntax/literate/AyaLiterate.java
Labels: resolving, literate

#1076 Coverage
  base/src/main/java/org/aya/primitive/PrimFactory.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
  base/src/main/java/org/aya/unify/TermComparator.java
  base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
  cli-impl/src/test/resources/success/src/Guide.aya
  ide-lsp/src/test/java/org/aya/lsp/LspTest.java
  ide-lsp/src/test/resources/lsp-test-lib/src/VecCore.aya
  jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/test/java/CompileTest.java
  syntax/src/main/java/module-info.java
  syntax/src/main/java/org/aya/syntax/compile/JitDef.java
  syntax/src/main/java/org/aya/syntax/compile/JitTele.java
  syntax/src/main/java/org/aya/syntax/core/Closure.java
  syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckAnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
  syntax/src/main/java/org/aya/syntax/core/term/LamTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/PiTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/Term.java
  syntax/src/main/java/org/aya/syntax/ref/DefVar.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
  syntax/src/main/java/org/aya/syntax/telescope/JitTele.java
  syntax/src/main/java/org/aya/syntax/telescope/Signature.java
Labels: test fixtures, jit

#1077 Improve literate mode support
  base/src/main/java/org/aya/tyck/ExprTycker.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
Labels: literate

#1078 Make `lift ref` work
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/error/MetaVarProblem.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/main/java/org/aya/unify/Unifier.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  cli-impl/src/test/java/org/aya/test/fixtures/ParseError.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  cli-impl/src/test/resources/negative/ParseError.txt
  cli-impl/src/test/resources/success/src/Guide.aya
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/syntax/core/term/SortTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/Term.java
Labels: test fixtures, tyck, mcbride universe

#1080 Chaotic library testing
  base/src/main/java/org/aya/resolve/visitor/PatternResolver.java
  base/src/main/java/org/aya/tyck/error/Goal.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
  base/src/main/java/org/aya/unify/TermComparator.java
  cli-impl/src/test/java/org/aya/test/fixtures/ExprTyckError.java
  cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
  cli-impl/src/test/java/org/aya/test/fixtures/PatCohError.java
  cli-impl/src/test/java/org/aya/test/fixtures/PatTyckError.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/java/org/aya/test/fixtures/TerckError.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  cli-impl/src/test/resources/negative/PatCohError.txt
  cli-impl/src/test/resources/negative/PatTyckError.txt
  cli-impl/src/test/resources/negative/TerckError.txt
  cli-impl/src/test/resources/shared/src/arith/Bool.aya
  cli-impl/src/test/resources/shared/src/arith/bool/base.aya
  cli-impl/src/test/resources/shared/src/arith/int/base.aya
  cli-impl/src/test/resources/shared/src/arith/nat/base.aya
  cli-impl/src/test/resources/shared/src/data/Interval.aya
  cli-impl/src/test/resources/shared/src/data/fmset/base.aya
  cli-impl/src/test/resources/shared/src/data/list/base.aya
  cli-impl/src/test/resources/shared/src/data/vec/base.aya
  cli-impl/src/test/resources/shared/src/data/vec/properties.aya
  cli-impl/src/test/resources/shared/src/paths.aya
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
  cli-impl/src/test/resources/success/src/Guide.aya
  cli-impl/src/test/resources/success/src/Test.aya
  jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
  syntax/src/main/java/org/aya/generic/stmt/Shaped.java
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/syntax/concrete/Pattern.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/core/def/AnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/ConDefLike.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
Labels: concrete: pattern, literate, library, mcbride universe, shape

#1082 Why did we play Haruhikage??
  base/src/main/java/org/aya/normalize/Finalizer.java
  base/src/main/java/org/aya/normalize/PatMatcher.java
  base/src/main/java/org/aya/tyck/error/ClausesProblem.java
  base/src/main/java/org/aya/tyck/error/Goal.java
  base/src/main/java/org/aya/tyck/error/UnifyInfo.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/tycker/Stateful.java
  base/src/main/java/org/aya/unify/Unifier.java
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  cli-impl/src/test/resources/negative/PatCohError.txt
  cli-impl/src/test/resources/shared/src/data/vec/properties.aya
  cli-impl/src/test/resources/shared/src/paths.aya
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/FindUsage.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
Labels: error report, meta variables

#1083 Makes fmset/base.aya work
  base/src/main/java/org/aya/normalize/Normalizer.java
  cli-impl/src/test/resources/shared/src/data/fmset/base.aya
Labels: bug

#1085 Resolve Elim in StmtResolver
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/test/java/org/aya/tyck/TyckTest.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/resources/negative/ScopeError.txt
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/FnBody.java
Labels: bug

#1086 Fix checkCon return type treatment
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/core/term/call/RuleReducer.java
  tools/src/main/java/org/aya/util/reporter/Problem.java
Labels: bug, tyck

#1088 Release v0.32
  gradle/libs.versions.toml
  note/early-changelog.md
Labels: release

#1089 Fix pretty print
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
Labels: pretty print

#1090 Serialize FnDef#modifiers
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  syntax/src/main/java/org/aya/syntax/compile/JitFn.java
  syntax/src/main/java/org/aya/syntax/core/def/FnDef.java
  syntax/src/main/java/org/aya/syntax/core/def/FnDefLike.java
Labels: serialization

#1091 Implement sameMeta unification
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/error/MetaVarProblem.java
  base/src/main/java/org/aya/unify/TermComparator.java
  base/src/main/java/org/aya/unify/Unifier.java
  cli-impl/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  syntax/src/main/java/org/aya/syntax/core/term/call/MetaCall.java
Labels: error report, meta variables

#1092 Re #568, make most of qiit tyck
  base/src/main/java/org/aya/tyck/ExprTycker.java
  cli-impl/src/test/resources/shared/src/arith/int/base.aya
  cli-impl/src/test/resources/shared/src/data/vec.aya
  cli-impl/src/test/resources/shared/src/paths.aya
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
  cli-impl/src/test/resources/success/src/Guide.aya
Labels: cubical

#1093 QIIT now works!!
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  cli-impl/src/test/java/org/aya/test/cli/ReplCompilerTest.java
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
Labels: library

#1094 Pretty print/literate mode features
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
  cli-impl/src/main/java/org/aya/cli/literate/FaithfulPrettier.java
  cli-impl/src/main/java/org/aya/cli/literate/HighlightInfo.java
  cli-impl/src/main/java/org/aya/cli/literate/SyntaxHighlight.java
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
  ide-lsp/src/main/java/org/aya/lsp/models/HighlightResult.java
  syntax/src/main/java/org/aya/syntax/concrete/Expr.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
  syntax/src/main/java/org/aya/syntax/telescope/JitTele.java
Labels: highlighter

#1095 More things in the lib, handle empty patterns
  cli-impl/src/test/resources/shared/src/arith/nat.aya
  cli-impl/src/test/resources/shared/src/arith/nat/base.aya
  cli-impl/src/test/resources/shared/src/arith/nat/properties.aya
  cli-impl/src/test/resources/shared/src/data/empty.aya
  cli-impl/src/test/resources/shared/src/data/list/base.aya
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
Labels: library

#1096 Renamer
  .github/README.md
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/pat/IApplyConfl.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  base/src/main/java/org/aya/unify/DoubleChecker.java
  base/src/main/java/org/aya/unify/Synthesizer.java
  base/src/main/java/org/aya/unify/TermComparator.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  syntax/src/main/java/org/aya/generic/NameGenerator.java
  syntax/src/main/java/org/aya/generic/Renamer.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/core/term/LamTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/PiTerm.java
  syntax/src/main/java/org/aya/syntax/ref/LocalCtx.java
  syntax/src/main/java/org/aya/syntax/ref/LocalCtx1.java
  syntax/src/main/java/org/aya/syntax/ref/MapLocalCtx.java
Labels: pretty print

#1097 Make serialized code substantially faster
  base/src/main/java/org/aya/normalize/Normalizer.java
  base/src/main/java/org/aya/resolve/module/DumbModuleLoader.java
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/FileSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/util/SerializeUtils.java
  jit-compiler/src/test/java/CompileTest.java
  jit-compiler/src/test/java/CompileTester.java
  jit-compiler/src/test/java/RedBlackTreeTest.java
  syntax/src/main/java/org/aya/generic/stmt/Reducible.java
  syntax/src/main/java/org/aya/generic/stmt/Shaped.java
  syntax/src/main/java/org/aya/syntax/compile/JitFn.java
  syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
Labels: jit

#1100 Give lambda parameters more reasonable names, implement Jit `ourCall`
  base/src/main/java/org/aya/tyck/pat/IApplyConfl.java
  cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  jit-compiler/src/main/java/org/aya/compiler/AbstractExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/AbstractSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/NameGenerator.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PrimSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/SourceBuilder.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  jit-compiler/src/test/java/CompileTest.java
  syntax/src/main/java/org/aya/syntax/core/term/LamTerm.java
  syntax/src/main/java/org/aya/syntax/core/term/call/Callable.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ConCall.java
  syntax/src/main/java/org/aya/syntax/core/term/call/DataCall.java
  syntax/src/main/java/org/aya/syntax/core/term/call/FnCall.java
  syntax/src/main/java/org/aya/syntax/core/term/call/PrimCall.java
Labels: pretty print

#1102 Reorganize library, create `prelude`
  base/src/main/java/org/aya/resolve/module/FileModuleLoader.java
  base/src/main/java/org/aya/tyck/error/Goal.java
  base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
  cli-impl/src/test/java/org/aya/test/fixtures/PatCohError.java
  cli-impl/src/test/java/org/aya/test/fixtures/PatTyckError.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/resources/shared/src/arith/bool.aya
  cli-impl/src/test/resources/shared/src/arith/bool/properties.aya
  cli-impl/src/test/resources/shared/src/arith/int/base.aya
  cli-impl/src/test/resources/shared/src/arith/nat/base.aya
  cli-impl/src/test/resources/shared/src/arith/nat/properties.aya
  cli-impl/src/test/resources/shared/src/data/fmset/base.aya
  cli-impl/src/test/resources/shared/src/data/interval.aya
  cli-impl/src/test/resources/shared/src/data/list/base.aya
  cli-impl/src/test/resources/shared/src/data/list/properties.aya
  cli-impl/src/test/resources/shared/src/data/vec/base.aya
  cli-impl/src/test/resources/shared/src/data/vec/properties.aya
  cli-impl/src/test/resources/shared/src/prelude.aya
  cli-impl/src/test/resources/shared/src/relation/binary/path.aya
  cli-impl/src/test/resources/shared/src/relation/nullary/empty.aya
  cli-impl/src/test/resources/shared/src/type-theory/qiit.aya
  cli-impl/src/test/resources/success/src/Guide.aya
  cli-impl/src/test/resources/success/src/Test.aya
  syntax/src/main/java/org/aya/syntax/ref/LocalCtx.java
  syntax/src/main/java/org/aya/syntax/ref/SeqLocalCtx.java
Labels: repl, library

#1103 Quotient and fmset ++-assoc
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/error/Goal.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/unify/Synthesizer.java
  base/src/main/java/org/aya/unify/TermComparator.java
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  cli-impl/src/test/resources/shared/src/algebra/free-group.aya
  cli-impl/src/test/resources/shared/src/data/fmset/base.aya
  cli-impl/src/test/resources/shared/src/relation/binary/quotient.aya
  tools-repl/src/main/java/org/aya/repl/Repl.java
Labels: bug, error report, library

#1104 Fix module name serialization
  base/src/main/java/org/aya/resolve/ResolveInfo.java
  cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
  cli-impl/src/test/resources/shared/src/relation/binary/path.aya
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/NameSerializer.java
  jit-compiler/src/test/java/CompileTest.java
  jit-compiler/src/test/java/MiscTest.java
Labels: library, jit

#1105 What am I doing
  LICENSE
  base/src/main/java/org/aya/tyck/order/AyaOrgaTycker.java
  base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
  cli-console/src/main/java/org/aya/cli/repl/jline/AyaCompleters.java
  cli-impl/src/main/java/org/aya/cli/library/LibraryCompiler.java
  cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
  parser/src/main/java/org/aya/parser/AyaParserDefinitionBase.java
  pretty/src/main/java/org/aya/pretty/backend/terminal/AdaptiveCliStylist.java
  pretty/src/main/java/org/aya/pretty/error/PrettyErrorConfig.java
  pretty/src/main/java/org/aya/pretty/printer/StyleFamily.java
  pretty/src/main/java/org/aya/pretty/style/AyaStyleFamily.java
  tools-md/src/main/java/org/aya/literate/parser/InterestingLanguage.java
  tools-repl/src/main/java/org/aya/repl/Command.java
  tools-repl/src/main/java/org/aya/repl/IO.java
  tools-repl/src/main/java/org/aya/repl/ReplCompleters.java
  tools/src/main/java/org/aya/util/Ordering.java
  tools/src/main/java/org/aya/util/error/Global.java
  tools/src/main/java/org/aya/util/tyck/OrgaTycker.java
  tools/src/main/java/org/aya/util/tyck/SccTycker.java
Labels: refactoring

#1106 Initial `class` related code
  base/src/main/java/org/aya/resolve/ResolveInfo.java
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/test/java/org/aya/syntax/concrete/SyntaxTest.java
  cli-impl/src/main/java/org/aya/cli/utils/LiteratePrettierOptions.java
  jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java
  jit-compiler/src/main/java/org/aya/compiler/ModuleSerializer.java
  parser/src/main/grammar/AyaPsiParser.bnf
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/generic/Constants.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/prettier/Tokens.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/ClassDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/DataDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/Decl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/FnDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/PrimDecl.java
  syntax/src/main/java/org/aya/syntax/core/Closure.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDef.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TopLevelDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckAnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ClassCall.java
  syntax/src/main/java/org/aya/syntax/ref/DefVar.java
  syntax/src/main/java/org/aya/syntax/ref/GeneralizedVar.java
  syntax/src/main/java/org/aya/syntax/ref/MemberVar.java
  syntax/src/main/java/org/aya/syntax/telescope/Signature.java
  tools-repl/src/main/java/org/aya/repl/Command.java
  tools-repl/src/main/java/org/aya/repl/ReplParser.java
Labels: classes

#1107 Increase coverage, more code on classes
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/resources/negative/ScopeError.txt
  syntax/src/main/java/org/aya/syntax/core/def/ClassDef.java
  syntax/src/main/java/org/aya/syntax/core/def/ConDef.java
  syntax/src/main/java/org/aya/syntax/core/def/DataDef.java
  syntax/src/main/java/org/aya/syntax/core/def/FnDef.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDef.java
  syntax/src/main/java/org/aya/syntax/core/def/PrimDef.java
  syntax/src/main/java/org/aya/syntax/core/def/SubLevelDef.java
  syntax/src/main/java/org/aya/syntax/ref/DefVar.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
Labels: classes

#1108 Refactor the design of `Decl`, redo `TeleDecl`
  base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/order/AyaSccTycker.java
  cli-impl/src/test/java/org/aya/test/fixtures/ExprTyckError.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  parser/src/main/gen/org/aya/parser/AyaPsiElementTypes.java
  parser/src/main/gen/org/aya/parser/AyaPsiParser.java
  parser/src/main/grammar/AyaPsiParser.bnf
  producer/src/main/java/org/aya/producer/AyaProducer.java
  syntax/src/main/java/org/aya/prettier/ConcretePrettier.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/StmtVisitor.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/ClassDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/ClassMember.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/DataCon.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/DataDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/Decl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/FnDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/PrimDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/TeleDecl.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckAnyDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
Labels: concrete, classes

#1109 Some bug fixes
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/pat/YouTrack.java
  cli-impl/src/test/java/org/aya/test/fixtures/ScopeError.java
  cli-impl/src/test/resources/negative/ScopeError.txt
  cli-impl/src/test/resources/shared/src/prelude.aya
  cli-impl/src/test/resources/success/src/Test.aya
  jit-compiler/src/main/java/org/aya/compiler/CompiledModule.java
  jit-compiler/src/main/java/org/aya/compiler/DataSerializer.java
  syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
Labels: bug

#1110 Cleverly create bind amount, not calculate them upon jIT
  base/src/main/java/org/aya/resolve/context/ModuleSymbol.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  cli-impl/src/test/java/org/aya/test/TestRunner.java
  cli-impl/src/test/java/org/aya/test/fixtures/ParseError.java
  cli-impl/src/test/resources/negative/ParseError.txt
  jit-compiler/src/main/java/org/aya/compiler/FnSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternExprializer.java
  jit-compiler/src/main/java/org/aya/compiler/PatternSerializer.java
  syntax/src/main/java/org/aya/syntax/core/pat/Pat.java
  syntax/src/main/java/org/aya/syntax/core/term/Term.java
Labels: jit

#1111 Release v0.33
  gradle/libs.versions.toml
  note/early-changelog.md
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
Labels: pretty print, release

#1112 Class resolve code
  base/src/main/java/org/aya/resolve/visitor/ExprResolver.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
Labels: classes

#1114 Class progress
  base/src/main/java/org/aya/normalize/Normalizer.java
  base/src/main/java/org/aya/resolve/visitor/StmtResolver.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/TyckState.java
  base/src/main/java/org/aya/tyck/error/Goal.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/main/java/org/aya/unify/Synthesizer.java
  base/src/main/java/org/aya/unify/TermComparator.java
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ExprializeUtils.java
  jit-compiler/src/main/java/org/aya/compiler/JitTeleSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDef.java
  syntax/src/main/java/org/aya/syntax/core/def/ClassDefLike.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDef.java
  syntax/src/main/java/org/aya/syntax/core/term/call/Callable.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ClassCall.java
  syntax/src/main/java/org/aya/syntax/core/term/call/FieldCall.java
  syntax/src/main/java/org/aya/syntax/ref/QName.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
Labels: classes

#1115 Classes progress
  base/src/main/java/org/aya/resolve/visitor/StmtPreResolver.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/main/java/org/aya/unify/TermComparator.java
  base/src/test/java/org/aya/tyck/TyckTest.java
  cli-impl/src/main/java/org/aya/cli/utils/LiterateData.java
  gradle/libs.versions.toml
  jit-compiler/src/main/java/org/aya/compiler/TermExprializer.java
  note/early-changelog.md
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/ClassDecl.java
  syntax/src/main/java/org/aya/syntax/concrete/stmt/decl/ClassMember.java
  syntax/src/main/java/org/aya/syntax/core/def/MemberDef.java
  syntax/src/main/java/org/aya/syntax/core/term/call/Callable.java
  syntax/src/main/java/org/aya/syntax/core/term/call/MemberCall.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
Labels: classes

#1116 Do not explicitly set encoding in build
  build.gradle.kts
  cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
  cli-impl/src/test/resources/negative/ExprTyckError.txt
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  cli-impl/src/test/resources/negative/OperatorError.txt
  cli-impl/src/test/resources/negative/ParseError.txt
  cli-impl/src/test/resources/negative/PatCohError.txt
  cli-impl/src/test/resources/negative/PatTyckError.txt
  cli-impl/src/test/resources/negative/ScopeError.txt
  cli-impl/src/test/resources/negative/TerckError.txt
Labels: cli

#1117 Display emoji in Windows Terminal
  cli-console/src/main/java/org/aya/cli/console/AnsiReporter.java
  cli-console/src/main/java/org/aya/cli/plct/PLCTReport.java
  cli-impl/src/main/java/org/aya/cli/single/CompilerFlags.java
  cli-impl/src/main/java/org/aya/cli/utils/CompilerUtil.java
  pretty/src/main/java/org/aya/pretty/backend/latex/DocTeXPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/md/DocMdPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/md/MdStyle.java
  pretty/src/main/java/org/aya/pretty/backend/string/ClosingStylist.java
  pretty/src/main/java/org/aya/pretty/backend/string/Cursor.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringPrinter.java
  pretty/src/main/java/org/aya/pretty/backend/string/StringStylist.java
  tools-repl/src/main/java/org/aya/repl/ReplUtil.java
  tools/src/main/java/org/aya/util/reporter/Reporter.java
Labels: cli, deps: jline

#1118 Classes are now kinda working
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  base/src/test/java/org/aya/tyck/TyckTest.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ClassCall.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
Labels: classes

#1119 Use closures in classes
  base/src/main/java/org/aya/tyck/Jdg.java
  base/src/main/java/org/aya/tyck/tycker/AppTycker.java
  syntax/src/main/java/org/aya/prettier/CorePrettier.java
  syntax/src/main/java/org/aya/syntax/core/term/call/ClassCall.java
Labels: classes

#1120 Some error report issues reported by Utensil Song
  base/src/main/java/org/aya/normalize/Finalizer.java
  base/src/main/java/org/aya/resolve/salt/ExprBinParser.java
  base/src/main/java/org/aya/tyck/ExprTycker.java
  base/src/main/java/org/aya/tyck/tycker/Contextful.java
  cli-impl/src/test/java/org/aya/test/fixtures/GoalAndMeta.java
  cli-impl/src/test/resources/negative/GoalAndMeta.txt
  syntax/src/main/java/org/aya/syntax/ref/MetaVar.java
  tools/src/main/java/org/aya/util/error/SourcePos.java
Labels: error report

#1123 Make jlink binary compile libraries
  base/src/main/java/org/aya/normalize/Normalizer.java
  base/src/main/java/org/aya/tyck/pat/IApplyConfl.java
  base/src/main/java/org/aya/tyck/pat/PatternTycker.java
  base/src/main/java/org/aya/tyck/pat/YouTrack.java
  build.gradle.kts
  cli-console/src/main/java/org/aya/cli/repl/AyaRepl.java
  cli-console/src/main/java/org/aya/cli/repl/ReplCommands.java
  cli-impl/build.gradle.kts
  cli-impl/src/main/java/module-info.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  cli-impl/src/main/java/org/aya/cli/library/incremental/DiskCompilerAdvisor.java
  ide-lsp/build.gradle.kts
  jit-compiler/src/main/java/org/aya/compiler/AyaSerializer.java
  jit-compiler/src/main/java/org/aya/compiler/ConSerializer.java
  syntax/build.gradle.kts
  syntax/src/main/java/org/aya/syntax/core/pat/BindEater.java
  syntax/src/main/java/org/aya/syntax/core/pat/PatMatcher.java
Labels: java, jit

#1122 Unify Signature with AbstractTele.Locns
  base/src/main/java/org/aya/tyck/StmtTycker.java
  base/src/main/java/org/aya/tyck/pat/ClauseTycker.java
  base/src/main/java/org/aya/tyck/tycker/AbstractTycker.java
  base/src/main/java/org/aya/tyck/tycker/TeleTycker.java
  syntax/src/main/java/org/aya/prettier/BasePrettier.java
  syntax/src/main/java/org/aya/syntax/core/def/PrimDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TopLevelDef.java
  syntax/src/main/java/org/aya/syntax/core/def/TyckDef.java
  syntax/src/main/java/org/aya/syntax/telescope/AbstractTele.java
  syntax/src/main/java/org/aya/syntax/telescope/Signature.java
Labels: refactoring

#1124 Do something maybe addresses Hoshino's goal
  base/src/main/java/org/aya/resolve/StmtResolvers.java
  base/src/main/java/org/aya/resolve/module/ModuleLoader.java
  cli-impl/src/main/java/org/aya/cli/interactive/ReplCompiler.java
  gradle/wrapper/gradle-wrapper.properties
Labels: refactoring

#1126 Upgrade build util
  gradle/libs.versions.toml
  producer/src/main/java/org/aya/producer/AyaProducer.java
  producer/src/main/java/org/aya/producer/ParserUtil.java
Labels: deps: upstream
